### PR TITLE
Added warning

### PR DESCRIPTION
**Pull request by ghost**
I finally made some scripting XD
I just added this warning for those who are dumb enough to paste random codes in their consoles

### CODE REVIEW

**Comment by ghost** [comment]
html editor - Google Chrome 9_11_2020 4_35_01 PM

**Comment by ghost** [comment]
i was considering adding some formatting but i'll leave it like that!

**Comment by Ihatr** [comment]
That looks good.

**Comment by ghost** [comment]
> That looks good.

Thanks. Someone is finally appreciating my work here smh

**Pull request merged**
